<?php

namespace Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class BumexBasicBundleEntityExpedienteProxy extends \Bumex\BasicBundle\Entity\Expediente implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }
    
    
    public function getId()
    {
        $this->__load();
        return parent::getId();
    }

    public function setExpediente($expediente)
    {
        $this->__load();
        return parent::setExpediente($expediente);
    }

    public function getExpediente()
    {
        $this->__load();
        return parent::getExpediente();
    }

    public function setNombre($nombre)
    {
        $this->__load();
        return parent::setNombre($nombre);
    }

    public function getNombre()
    {
        $this->__load();
        return parent::getNombre();
    }

    public function setNif($nif)
    {
        $this->__load();
        return parent::setNif($nif);
    }

    public function getNif()
    {
        $this->__load();
        return parent::getNif();
    }

    public function setLocalidad($localidad)
    {
        $this->__load();
        return parent::setLocalidad($localidad);
    }

    public function getLocalidad()
    {
        $this->__load();
        return parent::getLocalidad();
    }

    public function setFecha($fecha)
    {
        $this->__load();
        return parent::setFecha($fecha);
    }

    public function getFecha()
    {
        $this->__load();
        return parent::getFecha();
    }

    public function setMatricula($matricula)
    {
        $this->__load();
        return parent::setMatricula($matricula);
    }

    public function getMatricula()
    {
        $this->__load();
        return parent::getMatricula();
    }

    public function setEuros($euros)
    {
        $this->__load();
        return parent::setEuros($euros);
    }

    public function getEuros()
    {
        $this->__load();
        return parent::getEuros();
    }

    public function setPrecepto($precepto)
    {
        $this->__load();
        return parent::setPrecepto($precepto);
    }

    public function getPrecepto()
    {
        $this->__load();
        return parent::getPrecepto();
    }

    public function setArt($art)
    {
        $this->__load();
        return parent::setArt($art);
    }

    public function getArt()
    {
        $this->__load();
        return parent::getArt();
    }

    public function setPuntos($puntos)
    {
        $this->__load();
        return parent::setPuntos($puntos);
    }

    public function getPuntos()
    {
        $this->__load();
        return parent::getPuntos();
    }

    public function setReq($req)
    {
        $this->__load();
        return parent::setReq($req);
    }

    public function getReq()
    {
        $this->__load();
        return parent::getReq();
    }

    public function setCoincidencia($coincidencia)
    {
        $this->__load();
        return parent::setCoincidencia($coincidencia);
    }

    public function getCoincidencia()
    {
        $this->__load();
        return parent::getCoincidencia();
    }

    public function setEdicto(\Bumex\BasicBundle\Entity\Edicto $edicto)
    {
        $this->__load();
        return parent::setEdicto($edicto);
    }

    public function getEdicto()
    {
        $this->__load();
        return parent::getEdicto();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'expediente', 'nombre', 'nif', 'localidad', 'fecha', 'matricula', 'euros', 'precepto', 'art', 'puntos', 'req', 'coincidencia', 'edicto');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}