<<<<<<< HEAD
=======
GbmIndexBundle:
    resource: "@GbmIndexBundle/Resources/config/routing.yml"
    prefix:   /
    
>>>>>>> a97ea73652baf19da7e958cd7843e901f1aeffdf
# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
