<?php

namespace Bumex\BasicBundle\Entity\TextoEdicto;

use Doctrine\ORM\EntityRepository;

/**
 * EdictoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EdictoRepository extends EntityRepository
{
}