index:
    pattern:  /index/
    defaults: { _controller: BumexBasicBundle:Index:index }
    
expedientes:
    pattern:  /expedientes/
    defaults: {_controller: BumexBasicBundle:Index:expedientes}

historial:
    pattern:  /historial/
    defaults: {_controller: BumexBasicBundle:Index:historial}