index:
    pattern:  /index/
    defaults: { _controller: BumexBasicBundle:Index:index }
    
expedientes:
    pattern:  /expedientes/
    defaults: {_controller: BumexBasicBundle:Index:expedientes}

auto:
    pattern:  /auto/
    defaults: {_controller: BumexBasicBundle:Index:auto}

historial:
    pattern:  /historial/{page}
    defaults: {_controller: BumexBasicBundle:Index:historial, page: '1'}